name: Auto Update README

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update README with Current IST Time
      id: update-time
      run: |
        export TZ=Asia/Kolkata
        TIME=$(date +"%I:%M %p") # Format time as HH:MM AM/PM
        echo "🕛 Updated at $TIME IST" > README.md
        echo "::set-output name=UPDATED_TIME::🕛 Updated at $TIME IST"

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ steps.update-time.outputs.UPDATED_TIME }}
        commit_options: ''
        push_options: ''
        skip_fetch: true
        
