name: LIST Show
on:
  workflow_dispatch: null  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: install Mongo and requests
        run: pip install pymongo requests pandas
      - name: Run Python script
        run: python list.py        
